name: Template Cleanup

on:
  push:
    branches:
      - master

jobs:

  template-cleanup:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    timeout-minutes: 10

    if: github.event.repository.name != 'shopping-cart-template'
    steps:

      - name: Fetch sources
        uses: actions/checkout@v3

      - name: Create issues from sessions
        uses: ./.github/actions

      - name: Cleanup
        shell: bash
        run: |
          # Delete anything
          rm -rf docs .github/actions
          rm -f .github/workflows/template-cleanup.yaml

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Template cleanup"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}